# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.NetPulse
PackageVersion: 1.0.3
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: NetPulse
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: NetPulse
  Publisher: TAPATCH
  ProductCode: NetPulse
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\NetPulse'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/NetPulse-Setup-1.0.3.exe
  InstallerSha256: 645818CB2901415E1D54014000B56E145B0AAEF34C65871BD26D52841377300D
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
