# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.LinkMass
PackageVersion: 1.0.3
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: LinkMass
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: LinkMass
  Publisher: TAPATCH
  ProductCode: LinkMass
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\LinkMass'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/LinkMass-Setup-1.0.3.exe
  InstallerSha256: B072A6049B5A7968609924CDF35F05AE3931102067CDDC8EEA6E4EF8AA6DBBBD
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
