# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.NetPulse
PackageVersion: 1.0.2
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: NetPulse
ReleaseDate: '2026-09-30'
AppsAndFeaturesEntries:
- DisplayName: NetPulse
  Publisher: TAPATCH
  ProductCode: NetPulse
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\NetPulse'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/NetPulse-Setup-1.0.2.exe
  InstallerSha256: 16E6F9A5A537C10137002667630EFC4D8E1367409717C13A5CC89A489B542D35
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
