# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.ClickMeter
PackageVersion: 1.0.5
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: ClickMeter
ReleaseDate: '2026-10-02'
AppsAndFeaturesEntries:
- DisplayName: ClickMeter
  Publisher: TAPATCH
  ProductCode: ClickMeter
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\ClickMeter'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/ClickMeter-Setup-1.0.5.exe
  InstallerSha256: AB252A3DB9A766DBF55840482513ABC7FC9275FED87B1D0E50D506E08F24E547
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
