# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.WaveCheck
PackageVersion: 1.0.3
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: WaveCheck
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: WaveCheck
  Publisher: TAPATCH
  ProductCode: WaveCheck
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\WaveCheck'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/WaveCheck-Setup-1.0.3.exe
  InstallerSha256: 66645D64C5D16CF30958EE5B8600EB72A08EF4A6BF4182376F4B45B9FC005C54
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
