# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.ClickMeter
PackageVersion: 1.0.4
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: ClickMeter
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: ClickMeter
  Publisher: TAPATCH
  ProductCode: ClickMeter
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\ClickMeter'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/ClickMeter-Setup-1.0.4.exe
  InstallerSha256: F4342E4743B0E48F288ED9A63EEA240ED80C21E6F53A0599FE5FF55038E9E729
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
