# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.FlowDesk
PackageVersion: 1.0.2
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: FlowDesk
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: FlowDesk
  Publisher: TAPATCH
  ProductCode: FlowDesk
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\FlowDesk'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/FlowDesk-Setup-1.0.2.exe
  InstallerSha256: 8A6C6CE4C3AE5798F9E5B59186103498D5664C08BE210DB9FD7F57B8ED388113
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
