# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.Autrix
PackageVersion: 1.0.6
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Autrix
ReleaseDate: '2026-10-02'
AppsAndFeaturesEntries:
- DisplayName: Autrix
  Publisher: TAPATCH
  ProductCode: Autrix
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\Autrix'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/Autrix-Setup-1.0.6.exe
  InstallerSha256: 39C46005A46741C4EFCC6CEEB289C381702FD98E999BC73B9F8D2FB819389721
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
