# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.DownSample
PackageVersion: 1.0.2
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: DownSample
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: DownSample
  Publisher: TAPATCH
  ProductCode: DownSample
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\DownSample'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/DownSample-Setup-1.0.2.exe
  InstallerSha256: BA0D3FC38C564AE9ED2074A2CBA16BD910B012EDF9A3DDDE53CD13DE067C8EEB
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
