# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.ForeverCrypt
PackageVersion: 1.0.2
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: ForeverCrypt
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: ForeverCrypt
  Publisher: TAPATCH
  ProductCode: ForeverCrypt
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\ForeverCrypt'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/ForeverCrypt-Setup-1.0.2.exe
  InstallerSha256: BEFB4A81118A9C427A1F02FC95A767DB16E1F5B0CE97B683B10C148E7D62DED9
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
