# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.Autrix
PackageVersion: 1.0.5
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Autrix
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: Autrix
  Publisher: TAPATCH
  ProductCode: Autrix
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\Autrix'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/Autrix-Setup-1.0.5.exe
  InstallerSha256: 9B801ADC398A3C1E0AE818B1BF771B11325616D9216F048D63F2A582AB5C37FE
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
