# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.OpTask
PackageVersion: 1.0.2
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OpTask
ReleaseDate: '2026-10-01'
AppsAndFeaturesEntries:
- DisplayName: OpTask
  Publisher: TAPATCH
  ProductCode: OpTask
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\OpTask'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/OpTask-Setup-1.0.2.exe
  InstallerSha256: 6FE4D5F37E753263C247D1F89B518DE22FEF67C5732FD17AC57971D6707E8665
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
