# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TAPATCH.OpTask
PackageVersion: 1.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OpTask
ReleaseDate: '2026-09-30'
AppsAndFeaturesEntries:
- DisplayName: OpTask
  Publisher: TAPATCH
  ProductCode: OpTask
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\TAPATCH\OpTask'
Installers:
- Architecture: x64
  InstallerUrl: https://tapatch.com/downloads/OpTask-Setup-1.0.1.exe
  InstallerSha256: 3F2E22DCE9CB90DE7C24905FE61026A78E1A7B22E5D3268BB3D81A19CFF50B6A
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.12.0
